apiVersion: v1
kind: Service
metadata:
  name: spring-boot-admin
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    run: spring-boot-admin